spring:
  application:
    name: oauth2-notes
  datasource:
    url: jdbc:mysql://localhost:3306/oauth2notesdb?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: oauth2notesadmin
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: true
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: Ov23liW4reSGtjkJtEzc
            client-secret: 707fb1d72762733edf5c86d9fa1b2b476c922e09
            scope:
              - read:user
              - user:email
logging:
  level:
    org:
      springframework:
        security: TRACE
